name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - '*'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Check Java version
        run: java -version
      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo "$GITHUB_MAVEN_SETTINGS" > ~/.m2/settings.xml
        env:
          GITHUB_MAVEN_SETTINGS: ${{ secrets.MAVEN_SETTINGS }}

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Lint code
        run: mvn checkstyle:check || true

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Build project
        run: mvn clean install -DskipTests

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Run tests
        run: mvn test

  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Package application
        run: mvn clean package shade:shade
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: application-jar
          path: target/*.jar

  deploy:
    needs: package
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Deploy application
        run: mvn deploy -DskipTests
        env:
          MAVEN_SETTINGS: ${{ secrets.MAVEN_SETTINGS }}
